on: 
  push:
  pull_request:
  schedule: 
    - cron: '0 3 * * *' # every day at 3am
jobs:
  gotest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.17.x'
      - name: Install dependencies
        run: go build
      - name: Run tests
        run: go test -v
      - name: Run tests with race detector
        run: go test -v -race
