name: test

on:
  pull_request:
  push:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ '1.15' ]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go }}

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Get dependencies
      run: |
        go get golang.org/x/tools/cmd/cover
        go get github.com/mattn/goveralls

    - name: Format
      run: go fmt

    - name: Vet
      run: go vet

    - name: Test
      run: go test -race -v -covermode=atomic -coverprofile=coverage.out

    - name: actions-goveralls
      uses: shogo82148/actions-goveralls@v1.2.2
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
